Add Robust Linear Regression
TheAlgorithms/Jupyter pull request #50
Opened 2021-07-30 10:21 UTC by OngYL

2021-07-30 15:11 UTC, kunyaw12 approved these changes

2021-07-31 10:13 UTC, hritik5102 commented
Great work @OngYL 🙌🏻 
Congrats your PR has been merged 🎊

2021-07-31 10:21 UTC, hritik5102 requested changes

2021-07-31 10:21 UTC, hritik5102 commented on Contributors.md
> +Ong Yean Lin
There is no need of creating a contributors page. I'll mention each contributor in the readme itself.

2021-07-31 10:24 UTC, hritik5102 commented
@OngYL change the notebook path from `jupyter/Robust Linear Regression.ipynb` to `jupyter/machine_learning/Robust Linear Regression.ipynb`.  

Rename the file : `Robust Linear Regression.ipynb ` to `Robust-Linear-Regression.ipynb`

2021-07-31 10:26 UTC, hritik5102 commented
Use `git commit --amend --no-edit` to remove the conflicts of multiple commits. Read more about [here](https://www.atlassian.com/git/tutorials/rewriting-history#git-commit--amend)

2021-08-28 08:36 UTC, closed without merging